### ISSUE TITLE
Intro modal -> home

### ISSUE THREAD

**Issue by readyyyk** [readyyyk/ChaPy#35]
add ability to cancel entering chat with home button (now blocked with backdrop)

**Comment by readyyyk** [comment]
![Frame 1](https://github.com/readyyyk/ChaPy/assets/78100125/afc91558-a663-4f84-817c-f1665e32413a)

**Comment by rutulganatra** [comment]
If no one is working on this then I can work on this?

**Comment by readyyyk** [comment]
https://mui.com/material-ui/material-icons/?query=bac&selected=FirstPage

`src/routes/Chat/components/Modals/IntroModal.jsx`

**Comment by rutulganatra** [comment]
https://github.com/rutulganatra/ChaPy/pull/1#issue-1920755888
I have raised a pull request for this issue please review it once
@readyyyk

**Comment by rutulganatra** [comment]
#47
