### ISSUE TITLE
Shortcut Scanner

### ISSUE THREAD

**Issue by readyyyk** [readyyyk/ChaPy#42]
Add to `manifest.js` shortcut for scanning qr codes ('/scanner')

**Comment by ShatilKhan** [comment]
Hi @readyyyk , I'd like to work on this. Would be great if you can provide some more info

**Comment by readyyyk** [comment]
@ShatilKhan 
Adding shortcut for pwa is simple adding object to array of shortcuts in `manifest.js`

It needs icon, description and direction to __**/scanner**__ route
