### ISSUE TITLE
Camera Permission 

### ISSUE THREAD

**Issue by readyyyk** [readyyyk/ChaPy#44]
Add camera request permission in app

**Comment by CoderRedwing** [comment]
please elaborate this problem

**Comment by readyyyk** [comment]
@CoderRedwing 
In this task i assume adding some button that calls request permission for camera 

This is needed because in pwa (displayed standalone) camera doesn't work if not allowed in browser

The button should be situated in `/scanner` route (i think in the top right corner)

(mui.com -> button with the following property:  `sx={{p: .75, minWidth: 'unset', minHeight: 'unset'}}`)
